DROP TABLE EXTRA;
DROP TABLE SERVICIO;
DROP TABLE RESERVA;
DROP TABLE EMPLEADO;
DROP TABLE VEHICULO;
DROP TABLE TIPO_VEHICULO;
DROP TABLE CLIENTE;
DROP TABLE MODELO;
DROP TABLE MARCA;


CREATE TABLE MARCA (
    id INT PRIMARY KEY,
    nombre VARCHAR2(15)
);

CREATE TABLE MODELO (
    id INT PRIMARY KEY,
    nombre VARCHAR2(15),
	id_marca INT
);

CREATE TABLE CLIENTE (
    id INT PRIMARY KEY,
    identificacion VARCHAR2(32),
	nombre VARCHAR2(50),
	direccion VARCHAR2(50),
	telefono VARCHAR2(32),
	categoria INT
);

CREATE TABLE TIPO_VEHICULO(
	id INT PRIMARY KEY,
	tipo VARCHAR2(32),
	precio_lavado FLOAT
);

CREATE TABLE VEHICULO (
    id INT PRIMARY KEY,
    id_modelo INT,
	id_cliente INT,
	id_tipo INT,
	color INT,
	annio CHAR(4),
	comentarios VARCHAR(128)
);

CREATE TABLE EMPLEADO (
    id INT PRIMARY KEY,
    DUI CHAR(10),
	nombre VARCHAR2(50),
	direccion VARCHAR2(50),
	telefono CHAR(9),
	fecha_contrato DATE,
	salario FLOAT
);

CREATE TABLE SERVICIO (
    id INT PRIMARY KEY,
    servicio VARCHAR2(30),
	precio FLOAT
);

CREATE TABLE RESERVA (
    id INT PRIMARY KEY,
	id_vehiculo INT,
	id_empleado_responsable INT,
	fecha_transaccion TIMESTAMP,
	fecha_reservada TIMESTAMP,
	fecha_servicio_aplicado TIMESTAMP
);

CREATE TABLE EXTRA(
	id_reserva INT,
	id_servicio INT
);



ALTER TABLE MODELO ADD FOREIGN KEY(id_marca) REFERENCES MARCA(id);
ALTER TABLE VEHICULO ADD FOREIGN KEY(id_modelo) REFERENCES MODELO(id);
ALTER TABLE VEHICULO ADD FOREIGN KEY(id_tipo) REFERENCES TIPO_VEHICULO(id);
ALTER TABLE VEHICULO ADD FOREIGN KEY(id_cliente) REFERENCES CLIENTE(id);
ALTER TABLE RESERVA ADD FOREIGN KEY(id_vehiculo) REFERENCES VEHICULO(id);
ALTER TABLE RESERVA ADD FOREIGN KEY(id_empleado_responsable) REFERENCES EMPLEADO(id);
ALTER TABLE EXTRA ADD PRIMARY KEY (id_reserva, id_servicio);
ALTER TABLE EXTRA ADD FOREIGN KEY(id_reserva) REFERENCES RESERVA(id);
ALTER TABLE EXTRA ADD FOREIGN KEY(id_servicio) REFERENCES SERVICIO(id);

