CREATE TABLE CLASIFICACION(
	id INT PRIMARY KEY,
	titulo VARCHAR(32)
);

CREATE TABLE GENERO(
	id INT PRIMARY KEY,
	titulo VARCHAR(32)
);

CREATE TABLE TIPO_FUNCION(
	id INT PRIMARY KEY,
	tipo VARCHAR(32),
	precio MONEY
);

CREATE TABLE SALA(
	id INT PRIMARY KEY,
	nombre VARCHAR(16),
	ubicacion VARCHAR(32)
);

CREATE TABLE ASIENTO(
	id INT PRIMARY KEY,
	fila CHAR(1),
	columna INT,
	id_sala INT
);



CREATE TABLE PELICULA(
	id INT PRIMARY KEY,
	titulo VARCHAR(32),
	duracion VARCHAR(16),
	id_clasificacion INT,
	id_genero INT
);

CREATE TABLE FUNCION(
	id INT PRIMARY KEY,
	fecha_hora DATETIME,
	id_pelicula INT,
	id_sala INT,
	id_tipo INT
);

CREATE TABLE CARTELERA(
	id INT PRIMARY KEY,
	fecha_inicio DATE,
	fecha_fin DATE
);

CREATE TABLE ITEM_CARTELERA(
	id_funcion INT NOT NULL,
	id_cartelera INT NOT NULL,
);

CREATE TABLE ENTRADA(
	id INT PRIMARY KEY,
	codigo_validacion CHAR(6),
	id_funcion INT,
	id_asiento INT,
	id_compra INT
);

CREATE TABLE EMPLEADO(
	id INT PRIMARY KEY,
	nombre VARCHAR(64),
	direccion VARCHAR(128),
	fecha_nacimiento DATE,
	salario MONEY,
	fecha_contrato DATE
);

CREATE TABLE CLIENTE(
	id INT PRIMARY KEY,
	nombre VARCHAR(64),
	direccion VARCHAR(128),
	fecha_nacimiento DATE,
	correo VARCHAR(64)
);

CREATE TABLE COMPRA(
	id INT PRIMARY KEY,
	fecha DATETIME,
	descuento MONEY,
	id_cliente INT,
	id_empleado INT
);


CREATE TABLE PRODUCTO(
	id INT PRIMARY KEY,
	nombre VARCHAR(32),
	precio MONEY
);

CREATE TABLE COMBO (
	id INT PRIMARY KEY,
	nombre VARCHAR(64),
	precio MONEY
);

CREATE TABLE DETALLE_PRODUCTO(
	id_compra INT NOT NULL,
	id_producto INT NOT NULL,
	cantidad INT 
);

CREATE TABLE DETALLE_COMBO(
	id_compra INT NOT NULL,
	id_combo INT NOT NULL,
	cantidad INT 
);

CREATE TABLE ITEM_COMBO(
	id_producto INT NOT NULL,
	id_combo INT NOT NULL,
	cantidad INT 
);


-- DEFINICION DE RELACIONES
-- LLAVES PRIMARIAS
ALTER TABLE ITEM_CARTELERA ADD PRIMARY KEY (id_funcion, id_cartelera);
ALTER TABLE DETALLE_PRODUCTO ADD PRIMARY KEY (id_producto, id_compra);
ALTER TABLE DETALLE_COMBO ADD PRIMARY KEY (id_compra, id_combo);
ALTER TABLE ITEM_COMBO ADD PRIMARY KEY (id_producto, id_combo);
-- LLAVES FORANEAS
ALTER TABLE PELICULA ADD FOREIGN KEY (id_genero) REFERENCES GENERO (id);
ALTER TABLE PELICULA ADD FOREIGN KEY (id_clasificacion) REFERENCES CLASIFICACION (id);
ALTER TABLE FUNCION ADD FOREIGN KEY (id_tipo) REFERENCES TIPO_FUNCION (id);
ALTER TABLE FUNCION ADD FOREIGN KEY (id_pelicula) REFERENCES PELICULA (id);
ALTER TABLE FUNCION ADD FOREIGN KEY (id_sala) REFERENCES SALA (id);
ALTER TABLE ASIENTO ADD FOREIGN KEY (id_sala) REFERENCES SALA (id);
ALTER TABLE ITEM_CARTELERA ADD FOREIGN KEY (id_funcion) REFERENCES FUNCION (id);
ALTER TABLE ITEM_CARTELERA ADD FOREIGN KEY (id_cartelera) REFERENCES CARTELERA (id);
ALTER TABLE ENTRADA ADD FOREIGN KEY (id_funcion) REFERENCES FUNCION (id);
ALTER TABLE ENTRADA ADD FOREIGN KEY (id_asiento) REFERENCES ASIENTO (id);
ALTER TABLE ENTRADA ADD FOREIGN KEY (id_compra) REFERENCES COMPRA (id);
ALTER TABLE COMPRA ADD FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id);
ALTER TABLE COMPRA ADD FOREIGN KEY (id_empleado) REFERENCES EMPLEADO (id);
ALTER TABLE DETALLE_PRODUCTO ADD FOREIGN KEY (id_producto) REFERENCES PRODUCTO (id);
ALTER TABLE DETALLE_PRODUCTO ADD FOREIGN KEY (id_compra) REFERENCES COMPRA (id);
ALTER TABLE DETALLE_COMBO ADD FOREIGN KEY (id_compra) REFERENCES COMPRA (id);
ALTER TABLE DETALLE_COMBO ADD FOREIGN KEY (id_combo) REFERENCES COMBO (id);
ALTER TABLE ITEM_COMBO ADD FOREIGN KEY (id_producto) REFERENCES PRODUCTO (id);
ALTER TABLE ITEM_COMBO ADD FOREIGN KEY (id_combo) REFERENCES COMBO (id);








